name: PHP CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' # Set your PHP version
          extensions: mbstring, intl, pdo, mysql
          ini-values: post_max_size=256M, upload_max_filesize=256M
          coverage: none

      - name: Install Composer Dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Run Tests
        run: vendor/bin/phpunit --testdox
